version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Ubuntu1804
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\ommstats.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
- sh: >-
    cd $APPVEYOR_BUILD_FOLDER
    git submodule update --init --recursive
build_script:
- sh: dotnet publish -c $CONFIGURATION
artifacts:
- path: src\ommstats\bin\Release\netcoreapp3.0\publish
  name: gh-release
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: v$(appveyor_build_version)
  auth_token:
    secure: RcHNjuAh+92p+kAT8mfzoPN9sGS7U+hf4HGddfDGDoJVlgsSn7qcroHTrsJp1VMk
  artifact: gh-release
  draft: true
  force_update: true
  on:
    branch: master