version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_script:
- cmd: >-
    git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
    && cd %APPVEYOR_BUILD_FOLDER%
    && git checkout -qf %APPVEYOR_REPO_COMMIT%
    && git submodule update --init --recursive
dotnet_csproj:
  patch: true
  file: '**\ommstats.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- cmd: dotnet publish -c %CONFIGURATION%
artifacts:
- path: src\bin\$(configuration)\netcoreapp2.1\publish
  name: gh-release
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: v$(appveyor_build_version)
  auth_token:
    secure: yL6am9X6fH3tkMyXORFGKmkIknr6w+QNBo6wZ9TwGP9RE5iJ5VAUK6IuMvKNBWbb
  artifact: gh-release
  draft: true
  force_update: true
  on:
    branch: master