version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_script:
- ps: >-
    if(-not $env:appveyor_pull_request_number) {
      git clone -q --branch=$env:appveyor_repo_branch https://github.com/$env:appveyor_repo_name.git $env:appveyor_build_folder
      git checkout -qf $env:appveyor_repo_commit
    } else {
      git clone -q https://github.com/$env:appveyor_repo_name.git $env:appveyor_build_folder
      git fetch -q origin +refs/pull/$env:appveyor_pull_request_number/merge:
      git checkout -qf FETCH_HEAD
    }
    git submodule update --init --recursive
dotnet_csproj:
  patch: true
  file: '**\ommstats.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- cmd: dotnet publish -c %CONFIGURATION%
artifacts:
- path: src\bin\$(configuration)\netcoreapp2.1\publish
  name: gh-release
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: v$(appveyor_build_version)
  auth_token:
    secure: yL6am9X6fH3tkMyXORFGKmkIknr6w+QNBo6wZ9TwGP9RE5iJ5VAUK6IuMvKNBWbb
  artifact: gh-release
  draft: true
  force_update: true
  on:
    branch: master